### ISSUE TITLE
Question: webview support

### ISSUE THREAD

**Issue by goguda** [stripe/connect-js#102]
I just want to say, the timing of the connect elements in this package couldn't be better as we are right in the middle of building out our product with Stripe Connect, but this is going to make the onboarding process so much easier for us than continuing to build the custom forms we were building. Thank you so so much to the team who put this together!

Question, officially the [documentation](https://docs.stripe.com/connect/get-started-connect-embedded-components) does say that webviews aren't supported.

Is there something specific known about webviews that make the components not work correctly, or is this more of a "not officially tested but may work" situation?

I ask because we have both a website (React) and an app (React Native) where we're looking to support Connect onboarding. If we can use this in the app as well through WebViews, that would be awesome.

Whatever the verdict, again thank you so much for this. Even if it does turn out we can only use it on the website, it still makes our lives so much easier.

Just curious if there's any more info about why it wouldn't work within a webview.

**Comment by jorgea-stripe** [comment]
Longer term, it is our intent to release react native, iOS and Android SDKs. In the meantime, instead of using a webviews (which are not supported), we recommend linking out to a standalone browser webpage. There are several flows in embedded components that won't work in webviews (and it isn't an environment we test for), hence why we publicly document the lack of support in our [documentation](https://docs.stripe.com/connect/get-started-connect-embedded-components).
